CREATE EXTENSION postgis;
CREATE INDEX is_tf ON hive_posts_cache(is_travelfeed);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN country_code VARCHAR(2);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN city VARCHAR(100);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN suburb VARCHAR(100);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN geo_location geography(POINT,4326);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN latitude FLOAT(4);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN longitude FLOAT(4);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN osm_type VARCHAR(1);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN osm_id BIGINT;
-- ALTER TABLE "hive_posts_cache" ADD COLUMN subdivision VARCHAR(100);
-- ALTER TABLE "hive_posts_cache" ADD COLUMN is_travelfeed BOOLEAN;
-- ALTER TABLE "hive_posts_cache" ADD COLUMN curation_score INTEGER;